### ISSUE TITLE
Optimize event replay process

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1082]
The current `import-events` process takes ~18 hours to complete in the current production deployments. It requires the importing of the complete node event TSV into our tables while calculating re-orgs, and the complete subdomain data, which at the moment are very intense processes.

This issue tracks a series of efforts (represented by individual issues) to reduce the total replay time as much as possible:
- [x] https://github.com/hirosystems/stacks-blockchain-api/issues/1081
- [x] #1117
- [x] Reduce the amount of microblock processing done during replay
- [x] #1160
- [x] #1171
- [x] https://github.com/hirosystems/stacks-blockchain-api/issues/1121
- [x] #1126 
- [x] #990

**Comment by saralab** [comment]
Next Steps:  Try event replay without the preorg mode on develop. And release v5
