### ISSUE TITLE
[Stacks 2.1] Validate Rosetta compatibility with Stacks 2.1 changes

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1284]
Several PRs and some changes to the stacks-node likely break or cause unexpected behavior in the Rosetta layer. Once most Stacks 2.1 related changes are implemented, we need to create a test suite that generates various Stacks 2.1 behaviors (new coinbase tx type, smart-contract tx type, stx-transfer memo, etc), then tests the Rosetta components against those blocks and transactions.

Note: this issue _excludes_ PoX-2 changes for Rosetta, that is being tracked in https://github.com/hirosystems/stacks-blockchain-api/issues/1278

* [x] Ensure `versioned-smart-contract` tx types are parsed and have correct Rosetta responses, see https://github.com/hirosystems/stacks-blockchain-api/issues/1274
  * Done in https://github.com/hirosystems/stacks-blockchain-api/pull/1290
* [x] Ensure `coinbase-pay-to-alt` tx types are parsed and have correct Rosetta responses, see https://github.com/hirosystems/stacks-blockchain-api/issues/1275
  * Done in https://github.com/hirosystems/stacks-blockchain-api/pull/1290
* [x] Ensure memos in `stx-transfer-memo?` events are included in Rosetta responses, see https://github.com/hirosystems/stacks-blockchain-api/issues/1276
  * Done in https://github.com/hirosystems/stacks-blockchain-api/pull/1290

**Comment by zone117x** [comment]
Closed in https://github.com/hirosystems/stacks-blockchain-api/pull/1290
