### ISSUE TITLE
API LOAD TEST tracking ticket

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/stacks-blockchain-api#1697]
Scale up the staging environment to match production settings, and work with QA to understand the max rate limit of our APIs:

- [ ] Stacks Blockchain API
- [ ] Stacks Blockchain Node API (/v2)
- [ ] Token Metadata API

Skipping for now:
- [x] ~BTC Utility API~

https://github.com/hirosystems/devops/issues/1241

**Comment by sabbyanandan** [comment]
@smcclellan: The list appears to be in the right order of priority, but wanted to explicitly mention that we start with Ordinals API first. Also, let's please remove BTC utility from the list for Q3 (perhaps split it and create a new issue for it, for Q4?).
